---
- name: Install Apache
  hosts: web_servers
  become: true

  tasks:
  - name: Install Apache on Ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"

  - name: Install Apache on Amazon Linux
    yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "Amazon"

  - name: Install Apache on Debian
    apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Debian"
```